name: CI for AnvilCraftMod
on:
  push:
    paths:
      - common/**
      - fabric/**
      - forge/**
      - build.gradle
      - gradle.properties
      - settings.gradle
  pull_request:
    paths:
      - common/**
      - fabric/**
      - forge/**
      - build.gradle
      - gradle.properties
      - settings.gradle


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.1.0
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Java 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: zulu
          java-version: 17
      - name: Setup cache
        uses: actions/cache@v3.0.11
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        uses: gradle/gradle-build-action@v2.4.2
        env:
          GITHUB_RUN_NUMBER: ${{ vars.GITHUB_RUN_NUMBER }}
        with:
          arguments: build
      - name: Get Version
        id: version
        run: |
          MESSAGE=$(ls forge/build/libs/* | grep sources.jar -v | grep shadow.jar -v | grep slim.jar -v | awk -F 'gtceu-forge-|.jar' '{print $2}')
      - name: capture build artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: AnvilCraftMod ${{ steps.version.outputs.version }}
          path: |
            fabric/build/libs/!(*-@(dev|sources|javadoc|dev-shadow)).jar
            forge/build/libs/!(*-@(dev|sources|javadoc|dev-shadow)).jar

